// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admission_control.proto

package admission_control

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	shared "shared"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Additional statuses that are possible from admission control in addition
// to VM statuses.
type AdmissionControlStatus int32

const (
	AdmissionControlStatus_Accepted    AdmissionControlStatus = 0
	AdmissionControlStatus_Blacklisted AdmissionControlStatus = 1
	AdmissionControlStatus_Rejected    AdmissionControlStatus = 2
)

var AdmissionControlStatus_name = map[int32]string{
	0: "Accepted",
	1: "Blacklisted",
	2: "Rejected",
}

var AdmissionControlStatus_value = map[string]int32{
	"Accepted":    0,
	"Blacklisted": 1,
	"Rejected":    2,
}

func (x AdmissionControlStatus) String() string {
	return proto.EnumName(AdmissionControlStatus_name, int32(x))
}

func (AdmissionControlStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d13d6ff9aac892b4, []int{0}
}

// -----------------------------------------------------------------------------
// ---------------- Submit transaction
// -----------------------------------------------------------------------------
// The request for transaction submission.
type SubmitTransactionRequest struct {
	// Transaction signed by wallet.
	SignedTxn            *SignedTransaction `protobuf:"bytes,1,opt,name=signed_txn,json=signedTxn,proto3" json:"signed_txn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SubmitTransactionRequest) Reset()         { *m = SubmitTransactionRequest{} }
func (m *SubmitTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionRequest) ProtoMessage()    {}
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13d6ff9aac892b4, []int{0}
}

func (m *SubmitTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionRequest.Unmarshal(m, b)
}
func (m *SubmitTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionRequest.Merge(m, src)
}
func (m *SubmitTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionRequest.Size(m)
}
func (m *SubmitTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionRequest proto.InternalMessageInfo

func (m *SubmitTransactionRequest) GetSignedTxn() *SignedTransaction {
	if m != nil {
		return m.SignedTxn
	}
	return nil
}

// The response for transaction submission.
//
// How does a client know if their transaction was included?
// A response from the transaction submission only means that the transaction
// was successfully added to mempool, but not that it is guaranteed to be
// included in the chain.  Each transaction should include an expiration time in
// the signed transaction.  Let's call this T0.  As a client, I submit my
// transaction to a validator. I now need to poll for the transaction I
// submitted.  I can use the query that takes my account and sequence number. If
// I receive back that the transaction is completed, I will verify the proofs to
// ensure that this is the transaction I expected.  If I receive a response that
// my transaction is not yet completed, I must check the latest timestamp in the
// ledgerInfo that I receive back from the query.  If this time is greater than
// T0, I can be certain that my transaction will never be included.  If this
// time is less than T0, I need to continue polling.
type SubmitTransactionResponse struct {
	// The status of a transaction submission can either be a VM status, or
	// some other admission control/mempool specific status e.g. Blacklisted.
	//
	// Types that are valid to be assigned to Status:
	//	*SubmitTransactionResponse_VmStatus
	//	*SubmitTransactionResponse_AcStatus
	//	*SubmitTransactionResponse_MempoolStatus
	Status isSubmitTransactionResponse_Status `protobuf_oneof:"status"`
	// Public key(id) of the validator that processed this transaction
	ValidatorId          []byte   `protobuf:"bytes,4,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitTransactionResponse) Reset()         { *m = SubmitTransactionResponse{} }
func (m *SubmitTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionResponse) ProtoMessage()    {}
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13d6ff9aac892b4, []int{1}
}

func (m *SubmitTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionResponse.Unmarshal(m, b)
}
func (m *SubmitTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionResponse.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionResponse.Merge(m, src)
}
func (m *SubmitTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionResponse.Size(m)
}
func (m *SubmitTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionResponse proto.InternalMessageInfo

type isSubmitTransactionResponse_Status interface {
	isSubmitTransactionResponse_Status()
}

type SubmitTransactionResponse_VmStatus struct {
	VmStatus *VMStatus `protobuf:"bytes,1,opt,name=vm_status,json=vmStatus,proto3,oneof"`
}

type SubmitTransactionResponse_AcStatus struct {
	AcStatus AdmissionControlStatus `protobuf:"varint,2,opt,name=ac_status,json=acStatus,proto3,enum=admission_control.AdmissionControlStatus,oneof"`
}

type SubmitTransactionResponse_MempoolStatus struct {
	MempoolStatus shared.MempoolAddTransactionStatus `protobuf:"varint,3,opt,name=mempool_status,json=mempoolStatus,proto3,enum=mempool.MempoolAddTransactionStatus,oneof"`
}

func (*SubmitTransactionResponse_VmStatus) isSubmitTransactionResponse_Status() {}

func (*SubmitTransactionResponse_AcStatus) isSubmitTransactionResponse_Status() {}

func (*SubmitTransactionResponse_MempoolStatus) isSubmitTransactionResponse_Status() {}

func (m *SubmitTransactionResponse) GetStatus() isSubmitTransactionResponse_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SubmitTransactionResponse) GetVmStatus() *VMStatus {
	if x, ok := m.GetStatus().(*SubmitTransactionResponse_VmStatus); ok {
		return x.VmStatus
	}
	return nil
}

func (m *SubmitTransactionResponse) GetAcStatus() AdmissionControlStatus {
	if x, ok := m.GetStatus().(*SubmitTransactionResponse_AcStatus); ok {
		return x.AcStatus
	}
	return AdmissionControlStatus_Accepted
}

func (m *SubmitTransactionResponse) GetMempoolStatus() shared.MempoolAddTransactionStatus {
	if x, ok := m.GetStatus().(*SubmitTransactionResponse_MempoolStatus); ok {
		return x.MempoolStatus
	}
	return shared.MempoolAddTransactionStatus_Valid
}

func (m *SubmitTransactionResponse) GetValidatorId() []byte {
	if m != nil {
		return m.ValidatorId
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SubmitTransactionResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SubmitTransactionResponse_VmStatus)(nil),
		(*SubmitTransactionResponse_AcStatus)(nil),
		(*SubmitTransactionResponse_MempoolStatus)(nil),
	}
}

func init() {
	proto.RegisterEnum("admission_control.AdmissionControlStatus", AdmissionControlStatus_name, AdmissionControlStatus_value)
	proto.RegisterType((*SubmitTransactionRequest)(nil), "admission_control.SubmitTransactionRequest")
	proto.RegisterType((*SubmitTransactionResponse)(nil), "admission_control.SubmitTransactionResponse")
}

func init() { proto.RegisterFile("admission_control.proto", fileDescriptor_d13d6ff9aac892b4) }

var fileDescriptor_d13d6ff9aac892b4 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0x9b, 0x82, 0xa6, 0xf6, 0xb6, 0xac, 0xab, 0x35, 0x41, 0x28, 0x2f, 0xa5, 0xf0, 0x50,
	0xfe, 0x28, 0x48, 0xe5, 0x81, 0xe7, 0x0e, 0x21, 0x0d, 0x69, 0x7d, 0x69, 0x0b, 0xaf, 0x91, 0x67,
	0x5f, 0x3a, 0x43, 0x62, 0x1b, 0xfb, 0x36, 0x8c, 0x8f, 0xc1, 0xa7, 0xe4, 0x6b, 0xa0, 0x26, 0xce,
	0x56, 0x68, 0x40, 0x3c, 0x25, 0x39, 0xe7, 0xe4, 0x77, 0x9d, 0x73, 0x03, 0x0f, 0xb8, 0xcc, 0x95,
	0xf7, 0xca, 0xe8, 0x54, 0x18, 0x4d, 0xce, 0x64, 0x89, 0x75, 0x86, 0x0c, 0x1b, 0x1e, 0x18, 0xa3,
	0xd3, 0x0d, 0x52, 0xfa, 0x4d, 0xd1, 0x55, 0x6a, 0x9d, 0x31, 0x9f, 0xaa, 0xe0, 0xe8, 0x91, 0xbf,
	0xe2, 0x0e, 0xe5, 0xab, 0x1c, 0x73, 0x6b, 0x4c, 0x96, 0x7a, 0xe2, 0xb4, 0xf5, 0xc1, 0x1c, 0x92,
	0xe3, 0xda, 0x73, 0x41, 0xca, 0xe8, 0x20, 0x0d, 0x8a, 0x3c, 0x45, 0xe7, 0x8c, 0x0b, 0x99, 0xc9,
	0x0a, 0xe2, 0xd5, 0xf6, 0x32, 0x57, 0xb4, 0xbe, 0xcd, 0x2e, 0xf1, 0xeb, 0x16, 0x3d, 0xb1, 0x37,
	0x00, 0x5e, 0x6d, 0x34, 0xca, 0x94, 0xae, 0x75, 0x1c, 0x8d, 0xa3, 0x69, 0x6f, 0x16, 0x27, 0xf4,
	0xdd, 0xa2, 0x4f, 0x56, 0xa5, 0xb1, 0xff, 0x52, 0xb7, 0xca, 0xae, 0xaf, 0xf5, 0xe4, 0x47, 0x1b,
	0x1e, 0x36, 0x50, 0xbd, 0x35, 0xda, 0x23, 0x4b, 0xa0, 0x5b, 0xe4, 0xe1, 0xa4, 0x81, 0x3a, 0x08,
	0xd4, 0x8f, 0x8b, 0x55, 0x29, 0x9f, 0xb7, 0x96, 0x9d, 0x22, 0xaf, 0xee, 0xd9, 0x39, 0x74, 0xb9,
	0xa8, 0xf3, 0xed, 0x71, 0x34, 0x3d, 0x9e, 0x3d, 0x4b, 0x0e, 0x9b, 0x9b, 0xd7, 0xca, 0xdb, 0x4a,
	0xb8, 0x25, 0x71, 0x11, 0x48, 0x0b, 0x38, 0xfe, 0xbd, 0xa8, 0xf8, 0x4e, 0x89, 0x7b, 0x9a, 0x04,
	0x39, 0x59, 0x54, 0xd7, 0xb9, 0xdc, 0xff, 0xb4, 0x1b, 0xd2, 0xbd, 0x10, 0x0b, 0xb8, 0xc7, 0xd0,
	0x2f, 0x78, 0xa6, 0x24, 0x27, 0xe3, 0x52, 0x25, 0xe3, 0xbb, 0xe3, 0x68, 0xda, 0x5f, 0xf6, 0x6e,
	0xb4, 0xf7, 0xf2, 0xac, 0x03, 0x47, 0xd5, 0xa4, 0xe7, 0xef, 0xe0, 0x7e, 0xf3, 0x09, 0x59, 0x1f,
	0x3a, 0x73, 0x21, 0xd0, 0x12, 0xca, 0x93, 0x16, 0x1b, 0x40, 0xef, 0x2c, 0xe3, 0xe2, 0x4b, 0xa6,
	0xfc, 0x4e, 0x88, 0x76, 0xf6, 0x12, 0x3f, 0xa3, 0xd8, 0x3d, 0xb5, 0x67, 0x3f, 0x23, 0x38, 0xf9,
	0x93, 0xc3, 0x2c, 0x0c, 0x0f, 0xea, 0x66, 0x2f, 0x1a, 0x3a, 0xfa, 0xdb, 0xaa, 0x47, 0x2f, 0xff,
	0x2f, 0x5c, 0x6d, 0x70, 0xd2, 0x62, 0x1c, 0x4e, 0x3f, 0x58, 0xc9, 0x09, 0xd7, 0xe6, 0x82, 0x13,
	0x7a, 0xba, 0x40, 0xb9, 0x41, 0xc7, 0x26, 0x61, 0x91, 0x4d, 0x66, 0x3d, 0xeb, 0xc9, 0x3f, 0x33,
	0xf5, 0x88, 0xcb, 0xa3, 0xf2, 0x07, 0x7d, 0xfd, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xff, 0x7a,
	0x79, 0x25, 0x03, 0x00, 0x00,
}
