// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mempool.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddTransactionWithValidationRequest struct {
	// Transaction from a wallet
	SignedTxn *SignedTransaction `protobuf:"bytes,1,opt,name=signed_txn,json=signedTxn,proto3" json:"signed_txn,omitempty"`
	// Max amount of gas required to execute the transaction
	// Without running the program, it is very difficult to determine this number,
	// so we use the max gas specified by the signed transaction.
	// This field is still included separately from the signed transaction so that
	// if we have a better methodology in the future, we can more accurately
	// specify the max gas.
	MaxGasCost uint64 `protobuf:"varint,2,opt,name=max_gas_cost,json=maxGasCost,proto3" json:"max_gas_cost,omitempty"`
	// Latest sequence number of the involved account from state db.
	LatestSequenceNumber uint64 `protobuf:"varint,3,opt,name=latest_sequence_number,json=latestSequenceNumber,proto3" json:"latest_sequence_number,omitempty"`
	// Latest account balance of the involved account from state db.
	AccountBalance       uint64   `protobuf:"varint,4,opt,name=account_balance,json=accountBalance,proto3" json:"account_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTransactionWithValidationRequest) Reset()         { *m = AddTransactionWithValidationRequest{} }
func (m *AddTransactionWithValidationRequest) String() string { return proto.CompactTextString(m) }
func (*AddTransactionWithValidationRequest) ProtoMessage()    {}
func (*AddTransactionWithValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{0}
}

func (m *AddTransactionWithValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTransactionWithValidationRequest.Unmarshal(m, b)
}
func (m *AddTransactionWithValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTransactionWithValidationRequest.Marshal(b, m, deterministic)
}
func (m *AddTransactionWithValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTransactionWithValidationRequest.Merge(m, src)
}
func (m *AddTransactionWithValidationRequest) XXX_Size() int {
	return xxx_messageInfo_AddTransactionWithValidationRequest.Size(m)
}
func (m *AddTransactionWithValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTransactionWithValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTransactionWithValidationRequest proto.InternalMessageInfo

func (m *AddTransactionWithValidationRequest) GetSignedTxn() *SignedTransaction {
	if m != nil {
		return m.SignedTxn
	}
	return nil
}

func (m *AddTransactionWithValidationRequest) GetMaxGasCost() uint64 {
	if m != nil {
		return m.MaxGasCost
	}
	return 0
}

func (m *AddTransactionWithValidationRequest) GetLatestSequenceNumber() uint64 {
	if m != nil {
		return m.LatestSequenceNumber
	}
	return 0
}

func (m *AddTransactionWithValidationRequest) GetAccountBalance() uint64 {
	if m != nil {
		return m.AccountBalance
	}
	return 0
}

type AddTransactionWithValidationResponse struct {
	// The ledger version at the time of the transaction submitted. The submitted
	// transaction will have version bigger than this 'current_version'
	CurrentVersion uint64 `protobuf:"varint,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	// The result of the transaction submission
	Status               MempoolAddTransactionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=mempool.MempoolAddTransactionStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AddTransactionWithValidationResponse) Reset()         { *m = AddTransactionWithValidationResponse{} }
func (m *AddTransactionWithValidationResponse) String() string { return proto.CompactTextString(m) }
func (*AddTransactionWithValidationResponse) ProtoMessage()    {}
func (*AddTransactionWithValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{1}
}

func (m *AddTransactionWithValidationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTransactionWithValidationResponse.Unmarshal(m, b)
}
func (m *AddTransactionWithValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTransactionWithValidationResponse.Marshal(b, m, deterministic)
}
func (m *AddTransactionWithValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTransactionWithValidationResponse.Merge(m, src)
}
func (m *AddTransactionWithValidationResponse) XXX_Size() int {
	return xxx_messageInfo_AddTransactionWithValidationResponse.Size(m)
}
func (m *AddTransactionWithValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTransactionWithValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTransactionWithValidationResponse proto.InternalMessageInfo

func (m *AddTransactionWithValidationResponse) GetCurrentVersion() uint64 {
	if m != nil {
		return m.CurrentVersion
	}
	return 0
}

func (m *AddTransactionWithValidationResponse) GetStatus() MempoolAddTransactionStatus {
	if m != nil {
		return m.Status
	}
	return MempoolAddTransactionStatus_Valid
}

// -----------------------------------------------------------------------------
// ---------------- GetBlock
// -----------------------------------------------------------------------------
type GetBlockRequest struct {
	MaxBlockSize         uint64                  `protobuf:"varint,1,opt,name=max_block_size,json=maxBlockSize,proto3" json:"max_block_size,omitempty"`
	Transactions         []*TransactionExclusion `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetBlockRequest) Reset()         { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()    {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{2}
}

func (m *GetBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockRequest.Unmarshal(m, b)
}
func (m *GetBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockRequest.Merge(m, src)
}
func (m *GetBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockRequest.Size(m)
}
func (m *GetBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockRequest proto.InternalMessageInfo

func (m *GetBlockRequest) GetMaxBlockSize() uint64 {
	if m != nil {
		return m.MaxBlockSize
	}
	return 0
}

func (m *GetBlockRequest) GetTransactions() []*TransactionExclusion {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type GetBlockResponse struct {
	Block                *SignedTransactionsBlock `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetBlockResponse) Reset()         { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()    {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{3}
}

func (m *GetBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockResponse.Unmarshal(m, b)
}
func (m *GetBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockResponse.Merge(m, src)
}
func (m *GetBlockResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockResponse.Size(m)
}
func (m *GetBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockResponse proto.InternalMessageInfo

func (m *GetBlockResponse) GetBlock() *SignedTransactionsBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type TransactionExclusion struct {
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	SequenceNumber       uint64   `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionExclusion) Reset()         { *m = TransactionExclusion{} }
func (m *TransactionExclusion) String() string { return proto.CompactTextString(m) }
func (*TransactionExclusion) ProtoMessage()    {}
func (*TransactionExclusion) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{4}
}

func (m *TransactionExclusion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionExclusion.Unmarshal(m, b)
}
func (m *TransactionExclusion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionExclusion.Marshal(b, m, deterministic)
}
func (m *TransactionExclusion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionExclusion.Merge(m, src)
}
func (m *TransactionExclusion) XXX_Size() int {
	return xxx_messageInfo_TransactionExclusion.Size(m)
}
func (m *TransactionExclusion) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionExclusion.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionExclusion proto.InternalMessageInfo

func (m *TransactionExclusion) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *TransactionExclusion) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

// -----------------------------------------------------------------------------
// ---------------- CommitTransactions
// -----------------------------------------------------------------------------
type CommitTransactionsRequest struct {
	Transactions []*CommittedTransaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// agreed monotonic timestamp microseconds since the epoch for a committed block
	// used by Mempool to GC expired transactions
	BlockTimestampUsecs  uint64   `protobuf:"varint,2,opt,name=block_timestamp_usecs,json=blockTimestampUsecs,proto3" json:"block_timestamp_usecs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTransactionsRequest) Reset()         { *m = CommitTransactionsRequest{} }
func (m *CommitTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*CommitTransactionsRequest) ProtoMessage()    {}
func (*CommitTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{5}
}

func (m *CommitTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTransactionsRequest.Unmarshal(m, b)
}
func (m *CommitTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *CommitTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTransactionsRequest.Merge(m, src)
}
func (m *CommitTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_CommitTransactionsRequest.Size(m)
}
func (m *CommitTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTransactionsRequest proto.InternalMessageInfo

func (m *CommitTransactionsRequest) GetTransactions() []*CommittedTransaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *CommitTransactionsRequest) GetBlockTimestampUsecs() uint64 {
	if m != nil {
		return m.BlockTimestampUsecs
	}
	return 0
}

type CommitTransactionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTransactionsResponse) Reset()         { *m = CommitTransactionsResponse{} }
func (m *CommitTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*CommitTransactionsResponse) ProtoMessage()    {}
func (*CommitTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{6}
}

func (m *CommitTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTransactionsResponse.Unmarshal(m, b)
}
func (m *CommitTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *CommitTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTransactionsResponse.Merge(m, src)
}
func (m *CommitTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_CommitTransactionsResponse.Size(m)
}
func (m *CommitTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTransactionsResponse proto.InternalMessageInfo

type CommittedTransaction struct {
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	SequenceNumber       uint64   `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	IsRejected           bool     `protobuf:"varint,3,opt,name=is_rejected,json=isRejected,proto3" json:"is_rejected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommittedTransaction) Reset()         { *m = CommittedTransaction{} }
func (m *CommittedTransaction) String() string { return proto.CompactTextString(m) }
func (*CommittedTransaction) ProtoMessage()    {}
func (*CommittedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{7}
}

func (m *CommittedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommittedTransaction.Unmarshal(m, b)
}
func (m *CommittedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommittedTransaction.Marshal(b, m, deterministic)
}
func (m *CommittedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommittedTransaction.Merge(m, src)
}
func (m *CommittedTransaction) XXX_Size() int {
	return xxx_messageInfo_CommittedTransaction.Size(m)
}
func (m *CommittedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_CommittedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_CommittedTransaction proto.InternalMessageInfo

func (m *CommittedTransaction) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *CommittedTransaction) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *CommittedTransaction) GetIsRejected() bool {
	if m != nil {
		return m.IsRejected
	}
	return false
}

// -----------------------------------------------------------------------------
// ---------------- HealthCheck
// -----------------------------------------------------------------------------
type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{8}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type HealthCheckResponse struct {
	// Indicate whether Mempool is in healthy condition.
	IsHealthy            bool     `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{9}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetIsHealthy() bool {
	if m != nil {
		return m.IsHealthy
	}
	return false
}

func init() {
	proto.RegisterType((*AddTransactionWithValidationRequest)(nil), "mempool.AddTransactionWithValidationRequest")
	proto.RegisterType((*AddTransactionWithValidationResponse)(nil), "mempool.AddTransactionWithValidationResponse")
	proto.RegisterType((*GetBlockRequest)(nil), "mempool.GetBlockRequest")
	proto.RegisterType((*GetBlockResponse)(nil), "mempool.GetBlockResponse")
	proto.RegisterType((*TransactionExclusion)(nil), "mempool.TransactionExclusion")
	proto.RegisterType((*CommitTransactionsRequest)(nil), "mempool.CommitTransactionsRequest")
	proto.RegisterType((*CommitTransactionsResponse)(nil), "mempool.CommitTransactionsResponse")
	proto.RegisterType((*CommittedTransaction)(nil), "mempool.CommittedTransaction")
	proto.RegisterType((*HealthCheckRequest)(nil), "mempool.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "mempool.HealthCheckResponse")
}

func init() { proto.RegisterFile("mempool.proto", fileDescriptor_a84c3667d8c2093a) }

var fileDescriptor_a84c3667d8c2093a = []byte{
	// 657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5f, 0x4f, 0x13, 0x4f,
	0x14, 0xfd, 0x2d, 0xf0, 0xe3, 0xcf, 0x2d, 0x16, 0x1d, 0x2a, 0x29, 0x2b, 0x28, 0x59, 0x48, 0xe4,
	0x41, 0x4a, 0x2c, 0x24, 0xbe, 0xf8, 0x02, 0xc4, 0x40, 0x4c, 0xf4, 0x61, 0x8b, 0x90, 0xf8, 0xb2,
	0x99, 0xdd, 0x4e, 0xda, 0xd1, 0xdd, 0x9d, 0xba, 0xf7, 0x2e, 0x69, 0x49, 0xfc, 0x08, 0xbe, 0xf8,
	0x05, 0xfd, 0x1a, 0x3e, 0x9a, 0x9d, 0x99, 0x2e, 0x6d, 0xa9, 0x0d, 0x89, 0x2f, 0x6d, 0xe6, 0x9e,
	0x73, 0xe7, 0xcc, 0x9c, 0x73, 0x67, 0xe1, 0x51, 0x22, 0x92, 0x9e, 0x52, 0x71, 0xa3, 0x97, 0x29,
	0x52, 0x6c, 0xc9, 0x2e, 0xdd, 0x27, 0x94, 0xf1, 0x14, 0x79, 0x44, 0x52, 0xa5, 0x06, 0x73, 0x6b,
	0x16, 0x0b, 0x90, 0x38, 0xe5, 0x68, 0xaa, 0xde, 0x2f, 0x07, 0x76, 0x4f, 0xda, 0xed, 0xcb, 0x3b,
	0xfa, 0xb5, 0xa4, 0xee, 0x15, 0x8f, 0x65, 0x9b, 0x17, 0x2b, 0x5f, 0x7c, 0xcb, 0x05, 0x12, 0x7b,
	0x03, 0x80, 0xb2, 0x93, 0x8a, 0x76, 0x40, 0xfd, 0xb4, 0xee, 0xec, 0x38, 0xfb, 0x95, 0x66, 0xbd,
	0x41, 0x83, 0x9e, 0xc0, 0x46, 0x4b, 0x03, 0x23, 0x5b, 0xf8, 0x2b, 0x86, 0x7b, 0xd9, 0x4f, 0xd9,
	0x0e, 0xac, 0x26, 0xbc, 0x1f, 0x74, 0x38, 0x06, 0x91, 0x42, 0xaa, 0xcf, 0xed, 0x38, 0xfb, 0x0b,
	0x3e, 0x24, 0xbc, 0x7f, 0xce, 0xf1, 0x4c, 0x21, 0xb1, 0x63, 0xd8, 0x88, 0x39, 0x09, 0xa4, 0x00,
	0x0b, 0xb1, 0x34, 0x12, 0x41, 0x9a, 0x27, 0xa1, 0xc8, 0xea, 0xf3, 0x9a, 0x5b, 0x33, 0x68, 0xcb,
	0x82, 0x1f, 0x35, 0xc6, 0x5e, 0xc2, 0x1a, 0x8f, 0x22, 0x95, 0xa7, 0x14, 0x84, 0x3c, 0xe6, 0x69,
	0x24, 0xea, 0x0b, 0x9a, 0x5e, 0xb5, 0xe5, 0x53, 0x53, 0xf5, 0x7e, 0x38, 0xb0, 0x37, 0xfb, 0x86,
	0xd8, 0x53, 0x29, 0x8a, 0x62, 0xc7, 0x28, 0xcf, 0x32, 0x91, 0x52, 0x70, 0x23, 0x32, 0x94, 0xca,
	0xdc, 0x73, 0xc1, 0xaf, 0xda, 0xf2, 0x95, 0xa9, 0xb2, 0xb7, 0xb0, 0x68, 0x3c, 0xd4, 0x97, 0xa9,
	0x36, 0xf7, 0x1a, 0xc3, 0x14, 0x3e, 0x98, 0xff, 0x71, 0xb9, 0x96, 0xe6, 0xfa, 0xb6, 0xc7, 0xbb,
	0x85, 0xb5, 0x73, 0x41, 0xa7, 0xb1, 0x8a, 0xbe, 0x0e, 0xcd, 0xdd, 0x83, 0x6a, 0xe1, 0x51, 0x58,
	0xd4, 0x02, 0x94, 0xb7, 0xc2, 0x0a, 0x17, 0xce, 0x69, 0x62, 0x4b, 0xde, 0x0a, 0x76, 0x02, 0xab,
	0x23, 0xa9, 0x16, 0xe2, 0xf3, 0xfb, 0x95, 0xe6, 0x76, 0x29, 0x3e, 0x22, 0xf9, 0xae, 0x1f, 0xc5,
	0x79, 0x71, 0x56, 0x7f, 0xac, 0xc5, 0xbb, 0x80, 0xc7, 0x77, 0xda, 0xf6, 0xda, 0xc7, 0xf0, 0xbf,
	0x16, 0xb6, 0xa1, 0x3e, 0xff, 0x5b, 0xa8, 0x68, 0xda, 0x0c, 0xd9, 0xbb, 0x86, 0xda, 0x34, 0x3d,
	0xb6, 0x01, 0x8b, 0x28, 0xd2, 0xb6, 0xc8, 0xf4, 0x76, 0xab, 0xbe, 0x5d, 0x15, 0xe6, 0x4e, 0xa6,
	0x6b, 0x26, 0xa1, 0x8a, 0x63, 0xb9, 0x7a, 0x3f, 0x1d, 0xd8, 0x3c, 0x53, 0x49, 0x22, 0x69, 0x54,
	0x7b, 0xe8, 0xd4, 0xa4, 0x07, 0xce, 0x84, 0x07, 0xa6, 0x93, 0xc6, 0xa7, 0x71, 0xac, 0x85, 0x35,
	0xe1, 0xa9, 0x31, 0x9a, 0x64, 0x22, 0x90, 0x78, 0xd2, 0x0b, 0x72, 0x14, 0x11, 0xda, 0xf3, 0xac,
	0x6b, 0xf0, 0x72, 0x88, 0x7d, 0x2a, 0x20, 0x6f, 0x0b, 0xdc, 0x69, 0x67, 0x32, 0x0e, 0x7a, 0x7d,
	0xa8, 0x4d, 0xd3, 0xfd, 0x67, 0x2f, 0xd8, 0x0b, 0xa8, 0x48, 0x0c, 0x32, 0xf1, 0x45, 0x44, 0x24,
	0xda, 0xfa, 0x39, 0x2c, 0xfb, 0x20, 0xd1, 0xb7, 0x15, 0xaf, 0x06, 0xec, 0x42, 0xf0, 0x98, 0xba,
	0x67, 0x5d, 0x51, 0x8e, 0x93, 0x77, 0x0c, 0xeb, 0x63, 0x55, 0x1b, 0xf4, 0x36, 0x80, 0xc4, 0xa0,
	0xab, 0x91, 0x81, 0x3e, 0xd2, 0xb2, 0xbf, 0x22, 0xd1, 0x50, 0x07, 0xcd, 0xdf, 0x73, 0xb0, 0x64,
	0xe7, 0x97, 0x7d, 0x87, 0xad, 0x59, 0x4f, 0x86, 0xbd, 0x2a, 0x0d, 0x7f, 0xc0, 0xb7, 0xc3, 0x3d,
	0x78, 0x20, 0xdb, 0xda, 0xf9, 0x1f, 0x3b, 0x81, 0xe5, 0xe1, 0x98, 0xb2, 0x7a, 0xd9, 0x3c, 0xf1,
	0x6a, 0xdc, 0xcd, 0x29, 0x48, 0xb9, 0x45, 0x00, 0xec, 0x7e, 0x62, 0xcc, 0x9b, 0x18, 0x94, 0x29,
	0x23, 0xe6, 0xee, 0xce, 0xe4, 0x94, 0x02, 0xef, 0xa1, 0x32, 0x62, 0x32, 0x7b, 0x56, 0x76, 0xdd,
	0x0f, 0xc4, 0xdd, 0x9a, 0x0e, 0x0e, 0xf7, 0x3a, 0x3d, 0xfa, 0xfc, 0xba, 0x23, 0xa9, 0x9b, 0x87,
	0x8d, 0x48, 0x25, 0x87, 0x32, 0x49, 0x72, 0xe2, 0xa1, 0x8c, 0x25, 0x0d, 0x0e, 0xa4, 0x3a, 0xbc,
	0xe1, 0x79, 0x4c, 0x07, 0xb1, 0x0c, 0x33, 0x7e, 0x68, 0x7e, 0x3b, 0x59, 0x2f, 0x0a, 0x17, 0xf5,
	0x07, 0xfc, 0xe8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xdd, 0xec, 0xf2, 0x03, 0x06, 0x00,
	0x00,
}
