// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network_mempool.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MempoolSyncMsg represents the messages exchanging between validators to keep
// transactions in sync. The proto definition provides the spec on the wire so
// that others can implement their mempool service in various languages.
// Mempool service is responsible for sending and receiving MempoolSyncMsg
// across validators.
type MempoolSyncMsg struct {
	PeerId               []byte               `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Transactions         []*SignedTransaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MempoolSyncMsg) Reset()         { *m = MempoolSyncMsg{} }
func (m *MempoolSyncMsg) String() string { return proto.CompactTextString(m) }
func (*MempoolSyncMsg) ProtoMessage()    {}
func (*MempoolSyncMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b8370d64e68bdb, []int{0}
}

func (m *MempoolSyncMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MempoolSyncMsg.Unmarshal(m, b)
}
func (m *MempoolSyncMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MempoolSyncMsg.Marshal(b, m, deterministic)
}
func (m *MempoolSyncMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MempoolSyncMsg.Merge(m, src)
}
func (m *MempoolSyncMsg) XXX_Size() int {
	return xxx_messageInfo_MempoolSyncMsg.Size(m)
}
func (m *MempoolSyncMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MempoolSyncMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MempoolSyncMsg proto.InternalMessageInfo

func (m *MempoolSyncMsg) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *MempoolSyncMsg) GetTransactions() []*SignedTransaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*MempoolSyncMsg)(nil), "network.MempoolSyncMsg")
}

func init() { proto.RegisterFile("network_mempool.proto", fileDescriptor_26b8370d64e68bdb) }

var fileDescriptor_26b8370d64e68bdb = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x4b, 0x2d, 0x29,
	0xcf, 0x2f, 0xca, 0x8e, 0xcf, 0x4d, 0xcd, 0x2d, 0xc8, 0xcf, 0xcf, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x87, 0x0a, 0x4b, 0x09, 0x96, 0x14, 0x25, 0xe6, 0x15, 0x27, 0x26, 0x97, 0x64,
	0xe6, 0xe7, 0x41, 0xe4, 0x94, 0xd2, 0xb9, 0xf8, 0x7c, 0x21, 0x8a, 0x83, 0x2b, 0xf3, 0x92, 0x7d,
	0x8b, 0xd3, 0x85, 0xc4, 0xb9, 0xd8, 0x0b, 0x52, 0x53, 0x8b, 0xe2, 0x33, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x78, 0x82, 0xd8, 0x40, 0x5c, 0xcf, 0x14, 0x21, 0x1b, 0x2e, 0x1e, 0x24, 0xfd, 0xc5,
	0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x12, 0x7a, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x7a, 0xc1,
	0x99, 0xe9, 0x79, 0xa9, 0x29, 0x21, 0x08, 0x05, 0x41, 0x28, 0xaa, 0x9d, 0x8c, 0xa3, 0x0c, 0xd3,
	0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x33, 0x73, 0x73, 0x4b, 0x4b, 0x12,
	0x93, 0x32, 0x73, 0x32, 0x4b, 0x2a, 0x75, 0x33, 0xf3, 0xf5, 0xcb, 0x12, 0x4b, 0x73, 0x4a, 0x74,
	0x73, 0x32, 0x93, 0x8a, 0x12, 0xf5, 0x21, 0x64, 0x7a, 0x51, 0x41, 0x72, 0x12, 0x1b, 0xd8, 0x91,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x89, 0x8b, 0xb4, 0x26, 0xd9, 0x00, 0x00, 0x00,
}
