// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node_debug_interface.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetNodeDetailsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeDetailsRequest) Reset()         { *m = GetNodeDetailsRequest{} }
func (m *GetNodeDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeDetailsRequest) ProtoMessage()    {}
func (*GetNodeDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{0}
}

func (m *GetNodeDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeDetailsRequest.Unmarshal(m, b)
}
func (m *GetNodeDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeDetailsRequest.Merge(m, src)
}
func (m *GetNodeDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeDetailsRequest.Size(m)
}
func (m *GetNodeDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeDetailsRequest proto.InternalMessageInfo

type GetNodeDetailsResponse struct {
	Stats                map[string]string `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetNodeDetailsResponse) Reset()         { *m = GetNodeDetailsResponse{} }
func (m *GetNodeDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeDetailsResponse) ProtoMessage()    {}
func (*GetNodeDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{1}
}

func (m *GetNodeDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeDetailsResponse.Unmarshal(m, b)
}
func (m *GetNodeDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeDetailsResponse.Merge(m, src)
}
func (m *GetNodeDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeDetailsResponse.Size(m)
}
func (m *GetNodeDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeDetailsResponse proto.InternalMessageInfo

func (m *GetNodeDetailsResponse) GetStats() map[string]string {
	if m != nil {
		return m.Stats
	}
	return nil
}

type DumpJemallocHeapProfileRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpJemallocHeapProfileRequest) Reset()         { *m = DumpJemallocHeapProfileRequest{} }
func (m *DumpJemallocHeapProfileRequest) String() string { return proto.CompactTextString(m) }
func (*DumpJemallocHeapProfileRequest) ProtoMessage()    {}
func (*DumpJemallocHeapProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{2}
}

func (m *DumpJemallocHeapProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpJemallocHeapProfileRequest.Unmarshal(m, b)
}
func (m *DumpJemallocHeapProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpJemallocHeapProfileRequest.Marshal(b, m, deterministic)
}
func (m *DumpJemallocHeapProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpJemallocHeapProfileRequest.Merge(m, src)
}
func (m *DumpJemallocHeapProfileRequest) XXX_Size() int {
	return xxx_messageInfo_DumpJemallocHeapProfileRequest.Size(m)
}
func (m *DumpJemallocHeapProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpJemallocHeapProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpJemallocHeapProfileRequest proto.InternalMessageInfo

type DumpJemallocHeapProfileResponse struct {
	// Status code from jemalloc mallctl call. 0 indicates success.
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpJemallocHeapProfileResponse) Reset()         { *m = DumpJemallocHeapProfileResponse{} }
func (m *DumpJemallocHeapProfileResponse) String() string { return proto.CompactTextString(m) }
func (*DumpJemallocHeapProfileResponse) ProtoMessage()    {}
func (*DumpJemallocHeapProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{3}
}

func (m *DumpJemallocHeapProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpJemallocHeapProfileResponse.Unmarshal(m, b)
}
func (m *DumpJemallocHeapProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpJemallocHeapProfileResponse.Marshal(b, m, deterministic)
}
func (m *DumpJemallocHeapProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpJemallocHeapProfileResponse.Merge(m, src)
}
func (m *DumpJemallocHeapProfileResponse) XXX_Size() int {
	return xxx_messageInfo_DumpJemallocHeapProfileResponse.Size(m)
}
func (m *DumpJemallocHeapProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpJemallocHeapProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DumpJemallocHeapProfileResponse proto.InternalMessageInfo

func (m *DumpJemallocHeapProfileResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*GetNodeDetailsRequest)(nil), "debug.GetNodeDetailsRequest")
	proto.RegisterType((*GetNodeDetailsResponse)(nil), "debug.GetNodeDetailsResponse")
	proto.RegisterMapType((map[string]string)(nil), "debug.GetNodeDetailsResponse.StatsEntry")
	proto.RegisterType((*DumpJemallocHeapProfileRequest)(nil), "debug.DumpJemallocHeapProfileRequest")
	proto.RegisterType((*DumpJemallocHeapProfileResponse)(nil), "debug.DumpJemallocHeapProfileResponse")
}

func init() { proto.RegisterFile("node_debug_interface.proto", fileDescriptor_44a3c1322867efb7) }

var fileDescriptor_44a3c1322867efb7 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xb4, 0xe4, 0x05, 0xa7, 0x20, 0xb2, 0xa8, 0x2d, 0x41, 0x6d, 0x09, 0x28, 0xbd,
	0x34, 0xc5, 0xf6, 0x52, 0x3c, 0x78, 0xa8, 0x15, 0xff, 0x1c, 0x54, 0xe2, 0xcd, 0x4b, 0xd9, 0x24,
	0xd3, 0xb8, 0xba, 0xc9, 0xc6, 0xec, 0x6c, 0xa1, 0x5f, 0xc3, 0x6f, 0xe6, 0x37, 0x92, 0x26, 0x2d,
	0xa2, 0x98, 0x7a, 0x59, 0x76, 0x9f, 0x7d, 0x66, 0xe7, 0xf7, 0x0c, 0x0b, 0x4e, 0xaa, 0x22, 0x9c,
	0x46, 0x18, 0x98, 0x78, 0x2a, 0x52, 0xc2, 0x7c, 0xc6, 0x43, 0xf4, 0xb2, 0x5c, 0x91, 0x62, 0x76,
	0x21, 0xbb, 0x4d, 0xd8, 0xbb, 0x42, 0xba, 0x53, 0x11, 0x4e, 0x90, 0xb8, 0x90, 0xda, 0xc7, 0x37,
	0x83, 0x9a, 0xdc, 0x77, 0x0b, 0xf6, 0x7f, 0xde, 0xe8, 0x4c, 0xa5, 0x1a, 0xd9, 0x39, 0xd8, 0x9a,
	0x38, 0xe9, 0x96, 0xd5, 0xa9, 0x77, 0x1b, 0x83, 0xae, 0x57, 0x3c, 0xe5, 0xfd, 0xee, 0xf6, 0x1e,
	0x97, 0xd6, 0xcb, 0x94, 0xf2, 0x85, 0x5f, 0x96, 0x39, 0x23, 0x80, 0x2f, 0x91, 0xed, 0x40, 0xfd,
	0x15, 0x17, 0x2d, 0xab, 0x63, 0x75, 0xb7, 0xfc, 0xe5, 0x96, 0xed, 0x82, 0x3d, 0xe7, 0xd2, 0x60,
	0xab, 0x56, 0x68, 0xe5, 0xe1, 0xac, 0x36, 0xb2, 0xdc, 0x0e, 0x1c, 0x4d, 0x4c, 0x92, 0xdd, 0x62,
	0xc2, 0xa5, 0x54, 0xe1, 0x35, 0xf2, 0xec, 0x21, 0x57, 0x33, 0x21, 0x71, 0x8d, 0x3d, 0x86, 0x76,
	0xa5, 0x63, 0x85, 0xdf, 0x86, 0xc6, 0x92, 0xc3, 0xe8, 0x69, 0xa8, 0x22, 0x2c, 0x1a, 0xdb, 0x3e,
	0x94, 0xd2, 0x85, 0x8a, 0x70, 0xf0, 0x61, 0x01, 0x2b, 0x93, 0x04, 0x26, 0xbe, 0x59, 0xcf, 0x8d,
	0xdd, 0xc3, 0xf6, 0xf7, 0x88, 0xec, 0xa0, 0x22, 0x79, 0x81, 0xe2, 0x1c, 0x6e, 0x9c, 0x8b, 0xfb,
	0x8f, 0xbd, 0x40, 0xb3, 0x82, 0x95, 0x1d, 0xaf, 0x6a, 0x37, 0xa7, 0x75, 0x4e, 0xfe, 0xb2, 0xad,
	0x7b, 0x8d, 0x87, 0x4f, 0xa7, 0xb1, 0xa0, 0x67, 0x13, 0x78, 0xa1, 0x4a, 0xfa, 0x22, 0x49, 0x0c,
	0xf1, 0x40, 0x48, 0x41, 0x8b, 0x9e, 0x50, 0xfd, 0x39, 0x37, 0x92, 0x7a, 0x52, 0x04, 0x39, 0xef,
	0x97, 0x6b, 0x9c, 0x67, 0x61, 0xf0, 0xbf, 0xf8, 0x2a, 0xc3, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x18, 0x2a, 0xea, 0x3b, 0x48, 0x02, 0x00, 0x00,
}
