// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Int32 struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32) Reset()         { *m = Int32{} }
func (m *Int32) String() string { return proto.CompactTextString(m) }
func (*Int32) ProtoMessage()    {}
func (*Int32) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Int32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32.Unmarshal(m, b)
}
func (m *Int32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32.Marshal(b, m, deterministic)
}
func (m *Int32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32.Merge(m, src)
}
func (m *Int32) XXX_Size() int {
	return xxx_messageInfo_Int32.Size(m)
}
func (m *Int32) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32.DiscardUnknown(m)
}

var xxx_messageInfo_Int32 proto.InternalMessageInfo

func (m *Int32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int64 struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64) Reset()         { *m = Int64{} }
func (m *Int64) String() string { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()    {}
func (*Int64) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *Int64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64.Unmarshal(m, b)
}
func (m *Int64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64.Marshal(b, m, deterministic)
}
func (m *Int64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64.Merge(m, src)
}
func (m *Int64) XXX_Size() int {
	return xxx_messageInfo_Int64.Size(m)
}
func (m *Int64) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64.DiscardUnknown(m)
}

var xxx_messageInfo_Int64 proto.InternalMessageInfo

func (m *Int64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type UInt32 struct {
	Value                uint32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UInt32) Reset()         { *m = UInt32{} }
func (m *UInt32) String() string { return proto.CompactTextString(m) }
func (*UInt32) ProtoMessage()    {}
func (*UInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *UInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UInt32.Unmarshal(m, b)
}
func (m *UInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UInt32.Marshal(b, m, deterministic)
}
func (m *UInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UInt32.Merge(m, src)
}
func (m *UInt32) XXX_Size() int {
	return xxx_messageInfo_UInt32.Size(m)
}
func (m *UInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_UInt32.DiscardUnknown(m)
}

var xxx_messageInfo_UInt32 proto.InternalMessageInfo

func (m *UInt32) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type UInt64 struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UInt64) Reset()         { *m = UInt64{} }
func (m *UInt64) String() string { return proto.CompactTextString(m) }
func (*UInt64) ProtoMessage()    {}
func (*UInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *UInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UInt64.Unmarshal(m, b)
}
func (m *UInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UInt64.Marshal(b, m, deterministic)
}
func (m *UInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UInt64.Merge(m, src)
}
func (m *UInt64) XXX_Size() int {
	return xxx_messageInfo_UInt64.Size(m)
}
func (m *UInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_UInt64.DiscardUnknown(m)
}

var xxx_messageInfo_UInt64 proto.InternalMessageInfo

func (m *UInt64) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type SInt32 struct {
	Value                int32    `protobuf:"zigzag32,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SInt32) Reset()         { *m = SInt32{} }
func (m *SInt32) String() string { return proto.CompactTextString(m) }
func (*SInt32) ProtoMessage()    {}
func (*SInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *SInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SInt32.Unmarshal(m, b)
}
func (m *SInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SInt32.Marshal(b, m, deterministic)
}
func (m *SInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SInt32.Merge(m, src)
}
func (m *SInt32) XXX_Size() int {
	return xxx_messageInfo_SInt32.Size(m)
}
func (m *SInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_SInt32.DiscardUnknown(m)
}

var xxx_messageInfo_SInt32 proto.InternalMessageInfo

func (m *SInt32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type SInt64 struct {
	Value                int64    `protobuf:"zigzag64,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SInt64) Reset()         { *m = SInt64{} }
func (m *SInt64) String() string { return proto.CompactTextString(m) }
func (*SInt64) ProtoMessage()    {}
func (*SInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{5}
}

func (m *SInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SInt64.Unmarshal(m, b)
}
func (m *SInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SInt64.Marshal(b, m, deterministic)
}
func (m *SInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SInt64.Merge(m, src)
}
func (m *SInt64) XXX_Size() int {
	return xxx_messageInfo_SInt64.Size(m)
}
func (m *SInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_SInt64.DiscardUnknown(m)
}

var xxx_messageInfo_SInt64 proto.InternalMessageInfo

func (m *SInt64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Fixed32 struct {
	Value                uint32   `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fixed32) Reset()         { *m = Fixed32{} }
func (m *Fixed32) String() string { return proto.CompactTextString(m) }
func (*Fixed32) ProtoMessage()    {}
func (*Fixed32) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{6}
}

func (m *Fixed32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fixed32.Unmarshal(m, b)
}
func (m *Fixed32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fixed32.Marshal(b, m, deterministic)
}
func (m *Fixed32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fixed32.Merge(m, src)
}
func (m *Fixed32) XXX_Size() int {
	return xxx_messageInfo_Fixed32.Size(m)
}
func (m *Fixed32) XXX_DiscardUnknown() {
	xxx_messageInfo_Fixed32.DiscardUnknown(m)
}

var xxx_messageInfo_Fixed32 proto.InternalMessageInfo

func (m *Fixed32) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Fixed64 struct {
	Value                uint64   `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fixed64) Reset()         { *m = Fixed64{} }
func (m *Fixed64) String() string { return proto.CompactTextString(m) }
func (*Fixed64) ProtoMessage()    {}
func (*Fixed64) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{7}
}

func (m *Fixed64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fixed64.Unmarshal(m, b)
}
func (m *Fixed64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fixed64.Marshal(b, m, deterministic)
}
func (m *Fixed64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fixed64.Merge(m, src)
}
func (m *Fixed64) XXX_Size() int {
	return xxx_messageInfo_Fixed64.Size(m)
}
func (m *Fixed64) XXX_DiscardUnknown() {
	xxx_messageInfo_Fixed64.DiscardUnknown(m)
}

var xxx_messageInfo_Fixed64 proto.InternalMessageInfo

func (m *Fixed64) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Boolean struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boolean) Reset()         { *m = Boolean{} }
func (m *Boolean) String() string { return proto.CompactTextString(m) }
func (*Boolean) ProtoMessage()    {}
func (*Boolean) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{8}
}

func (m *Boolean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boolean.Unmarshal(m, b)
}
func (m *Boolean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boolean.Marshal(b, m, deterministic)
}
func (m *Boolean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boolean.Merge(m, src)
}
func (m *Boolean) XXX_Size() int {
	return xxx_messageInfo_Boolean.Size(m)
}
func (m *Boolean) XXX_DiscardUnknown() {
	xxx_messageInfo_Boolean.DiscardUnknown(m)
}

var xxx_messageInfo_Boolean proto.InternalMessageInfo

func (m *Boolean) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Strings struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Strings) Reset()         { *m = Strings{} }
func (m *Strings) String() string { return proto.CompactTextString(m) }
func (*Strings) ProtoMessage()    {}
func (*Strings) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{9}
}

func (m *Strings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Strings.Unmarshal(m, b)
}
func (m *Strings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Strings.Marshal(b, m, deterministic)
}
func (m *Strings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Strings.Merge(m, src)
}
func (m *Strings) XXX_Size() int {
	return xxx_messageInfo_Strings.Size(m)
}
func (m *Strings) XXX_DiscardUnknown() {
	xxx_messageInfo_Strings.DiscardUnknown(m)
}

var xxx_messageInfo_Strings proto.InternalMessageInfo

func (m *Strings) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Bytes struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{10}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Repeated struct {
	Value                []*Int32 `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repeated) Reset()         { *m = Repeated{} }
func (m *Repeated) String() string { return proto.CompactTextString(m) }
func (*Repeated) ProtoMessage()    {}
func (*Repeated) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{11}
}

func (m *Repeated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repeated.Unmarshal(m, b)
}
func (m *Repeated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repeated.Marshal(b, m, deterministic)
}
func (m *Repeated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repeated.Merge(m, src)
}
func (m *Repeated) XXX_Size() int {
	return xxx_messageInfo_Repeated.Size(m)
}
func (m *Repeated) XXX_DiscardUnknown() {
	xxx_messageInfo_Repeated.DiscardUnknown(m)
}

var xxx_messageInfo_Repeated proto.InternalMessageInfo

func (m *Repeated) GetValue() []*Int32 {
	if m != nil {
		return m.Value
	}
	return nil
}

type Structs struct {
	A                    *Int32   `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    *UInt32  `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C                    *SInt32  `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	D                    *Fixed32 `protobuf:"bytes,4,opt,name=d,proto3" json:"d,omitempty"`
	E                    *Boolean `protobuf:"bytes,5,opt,name=e,proto3" json:"e,omitempty"`
	F                    *Strings `protobuf:"bytes,6,opt,name=f,proto3" json:"f,omitempty"`
	G                    *Bytes   `protobuf:"bytes,7,opt,name=g,proto3" json:"g,omitempty"`
	H                    []*Int32 `protobuf:"bytes,8,rep,name=h,proto3" json:"h,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Structs) Reset()         { *m = Structs{} }
func (m *Structs) String() string { return proto.CompactTextString(m) }
func (*Structs) ProtoMessage()    {}
func (*Structs) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{12}
}

func (m *Structs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Structs.Unmarshal(m, b)
}
func (m *Structs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Structs.Marshal(b, m, deterministic)
}
func (m *Structs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Structs.Merge(m, src)
}
func (m *Structs) XXX_Size() int {
	return xxx_messageInfo_Structs.Size(m)
}
func (m *Structs) XXX_DiscardUnknown() {
	xxx_messageInfo_Structs.DiscardUnknown(m)
}

var xxx_messageInfo_Structs proto.InternalMessageInfo

func (m *Structs) GetA() *Int32 {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *Structs) GetB() *UInt32 {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *Structs) GetC() *SInt32 {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *Structs) GetD() *Fixed32 {
	if m != nil {
		return m.D
	}
	return nil
}

func (m *Structs) GetE() *Boolean {
	if m != nil {
		return m.E
	}
	return nil
}

func (m *Structs) GetF() *Strings {
	if m != nil {
		return m.F
	}
	return nil
}

func (m *Structs) GetG() *Bytes {
	if m != nil {
		return m.G
	}
	return nil
}

func (m *Structs) GetH() []*Int32 {
	if m != nil {
		return m.H
	}
	return nil
}

func init() {
	proto.RegisterType((*Int32)(nil), "test.Int32")
	proto.RegisterType((*Int64)(nil), "test.Int64")
	proto.RegisterType((*UInt32)(nil), "test.UInt32")
	proto.RegisterType((*UInt64)(nil), "test.UInt64")
	proto.RegisterType((*SInt32)(nil), "test.SInt32")
	proto.RegisterType((*SInt64)(nil), "test.SInt64")
	proto.RegisterType((*Fixed32)(nil), "test.Fixed32")
	proto.RegisterType((*Fixed64)(nil), "test.Fixed64")
	proto.RegisterType((*Boolean)(nil), "test.Boolean")
	proto.RegisterType((*Strings)(nil), "test.Strings")
	proto.RegisterType((*Bytes)(nil), "test.Bytes")
	proto.RegisterType((*Repeated)(nil), "test.Repeated")
	proto.RegisterType((*Structs)(nil), "test.Structs")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd2, 0xbf, 0x6e, 0xc2, 0x30,
	0x10, 0x06, 0x70, 0x5d, 0x21, 0x81, 0x1a, 0x18, 0x6a, 0x75, 0x70, 0x5b, 0xf5, 0xef, 0xc4, 0x02,
	0xa8, 0x50, 0xf5, 0x01, 0x18, 0x2a, 0x75, 0x0d, 0x62, 0xe9, 0x66, 0x27, 0x26, 0x58, 0x0a, 0x18,
	0x85, 0x0b, 0x2a, 0x8f, 0xdc, 0xb7, 0xa8, 0xec, 0x38, 0xaa, 0x71, 0x59, 0x10, 0xd1, 0xef, 0xbb,
	0x8b, 0xf3, 0x25, 0x84, 0xa0, 0xdc, 0xe3, 0x78, 0x57, 0x6a, 0xd4, 0xb4, 0x6d, 0xfe, 0xbf, 0xdc,
	0x93, 0xe8, 0x73, 0x8b, 0xb3, 0x29, 0xbd, 0x26, 0xd1, 0x81, 0x17, 0x95, 0x64, 0xf0, 0x04, 0xc3,
	0x28, 0xa9, 0x2f, 0x1c, 0xbf, 0xbf, 0x9d, 0x72, 0xab, 0xe1, 0x07, 0x12, 0x2f, 0xcf, 0x8c, 0x0f,
	0x02, 0x0f, 0xe7, 0xdb, 0x9e, 0x2f, 0xce, 0xcc, 0x5f, 0x05, 0x1e, 0xce, 0xd3, 0xc6, 0x1f, 0x49,
	0xe7, 0x43, 0x7d, 0xcb, 0x2c, 0x5c, 0xd0, 0x09, 0x03, 0xe1, 0x86, 0xd8, 0x0b, 0xcc, 0xb5, 0x2e,
	0x24, 0xdf, 0x9e, 0x06, 0xba, 0x5e, 0x60, 0x81, 0xa5, 0xda, 0xe6, 0xfb, 0xd3, 0xc0, 0xa5, 0x57,
	0xd1, 0xfc, 0x88, 0x32, 0xe0, 0x7e, 0xc3, 0x23, 0xd2, 0x4d, 0xe4, 0x4e, 0x72, 0x94, 0x19, 0x7d,
	0xfe, 0x4b, 0xb4, 0x86, 0xbd, 0x69, 0x6f, 0x6c, 0x5f, 0x87, 0x2d, 0xa0, 0x89, 0xff, 0x80, 0xbd,
	0x5f, 0x95, 0xe2, 0x9e, 0xde, 0x10, 0xe0, 0x76, 0x59, 0x10, 0x05, 0x4e, 0x6f, 0x09, 0x08, 0x76,
	0x61, 0xa9, 0x5f, 0xd3, 0xd2, 0x99, 0x30, 0x96, 0xb2, 0x96, 0x6f, 0x0b, 0x67, 0x29, 0xbd, 0x23,
	0x90, 0xb1, 0xb6, 0xb5, 0x41, 0x6d, 0xae, 0xbf, 0x04, 0x32, 0x83, 0x92, 0x45, 0x3e, 0xba, 0x6a,
	0x12, 0x90, 0x06, 0x57, 0x2c, 0xf6, 0xd1, 0xd5, 0x92, 0xc0, 0xca, 0x9c, 0x34, 0x67, 0x1d, 0xff,
	0xa4, 0xb6, 0x92, 0x04, 0x72, 0x43, 0x6b, 0xd6, 0xfd, 0xff, 0xbc, 0xb0, 0x9e, 0xcf, 0xbe, 0x5e,
	0x73, 0x85, 0xeb, 0x4a, 0x8c, 0x53, 0xbd, 0x99, 0xa8, 0xcd, 0xa6, 0x42, 0x2e, 0x54, 0xa1, 0xf0,
	0x38, 0x52, 0x7a, 0x72, 0xe0, 0x55, 0x81, 0xa3, 0x42, 0x89, 0x92, 0x4f, 0xea, 0xdf, 0xbc, 0xdc,
	0xa5, 0x22, 0xb6, 0x5f, 0xef, 0xec, 0x37, 0x00, 0x00, 0xff, 0xff, 0xec, 0x0d, 0x61, 0x02, 0xcb,
	0x02, 0x00, 0x00,
}
