// Code generated by protoc-gen-go. DO NOT EDIT.
// source: validator_public_keys.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Protobuf definition for the Rust struct ValidatorPublicKeys
type ValidatorPublicKeys struct {
	// Validator account address
	AccountAddress []byte `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	// Consensus public key
	ConsensusPublicKey []byte `protobuf:"bytes,2,opt,name=consensus_public_key,json=consensusPublicKey,proto3" json:"consensus_public_key,omitempty"`
	// Network signing publick key
	NetworkSigningPublicKey []byte `protobuf:"bytes,3,opt,name=network_signing_public_key,json=networkSigningPublicKey,proto3" json:"network_signing_public_key,omitempty"`
	/// Network identity publick key
	NetworkIdentityPublicKey []byte   `protobuf:"bytes,4,opt,name=network_identity_public_key,json=networkIdentityPublicKey,proto3" json:"network_identity_public_key,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *ValidatorPublicKeys) Reset()         { *m = ValidatorPublicKeys{} }
func (m *ValidatorPublicKeys) String() string { return proto.CompactTextString(m) }
func (*ValidatorPublicKeys) ProtoMessage()    {}
func (*ValidatorPublicKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e933cd90ba9d127, []int{0}
}

func (m *ValidatorPublicKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorPublicKeys.Unmarshal(m, b)
}
func (m *ValidatorPublicKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorPublicKeys.Marshal(b, m, deterministic)
}
func (m *ValidatorPublicKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorPublicKeys.Merge(m, src)
}
func (m *ValidatorPublicKeys) XXX_Size() int {
	return xxx_messageInfo_ValidatorPublicKeys.Size(m)
}
func (m *ValidatorPublicKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorPublicKeys.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorPublicKeys proto.InternalMessageInfo

func (m *ValidatorPublicKeys) GetAccountAddress() []byte {
	if m != nil {
		return m.AccountAddress
	}
	return nil
}

func (m *ValidatorPublicKeys) GetConsensusPublicKey() []byte {
	if m != nil {
		return m.ConsensusPublicKey
	}
	return nil
}

func (m *ValidatorPublicKeys) GetNetworkSigningPublicKey() []byte {
	if m != nil {
		return m.NetworkSigningPublicKey
	}
	return nil
}

func (m *ValidatorPublicKeys) GetNetworkIdentityPublicKey() []byte {
	if m != nil {
		return m.NetworkIdentityPublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*ValidatorPublicKeys)(nil), "types.ValidatorPublicKeys")
}

func init() { proto.RegisterFile("validator_public_keys.proto", fileDescriptor_5e933cd90ba9d127) }

var fileDescriptor_5e933cd90ba9d127 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0xbf, 0x4b, 0xc4, 0x30,
	0x14, 0xc0, 0x71, 0xea, 0xaf, 0x21, 0x88, 0x42, 0x14, 0x2c, 0xde, 0x22, 0x2e, 0xba, 0xdc, 0x55,
	0xb9, 0x51, 0x1c, 0x74, 0x13, 0x17, 0x51, 0x70, 0x70, 0x29, 0x49, 0x1a, 0xea, 0xe3, 0xd2, 0xbc,
	0x92, 0xf7, 0x72, 0x92, 0xff, 0xd9, 0x3f, 0x42, 0x48, 0x7b, 0xb5, 0x4b, 0x86, 0x97, 0xef, 0x27,
	0x81, 0x27, 0x16, 0x5b, 0xe5, 0xa0, 0x51, 0x8c, 0xa1, 0xee, 0xa3, 0x76, 0x60, 0xea, 0x8d, 0x4d,
	0xb4, 0xea, 0x03, 0x32, 0xca, 0x43, 0x4e, 0xbd, 0xa5, 0xeb, 0xdf, 0x42, 0x9c, 0x7d, 0xee, 0xb2,
	0xb7, 0x5c, 0xbd, 0xda, 0x44, 0xf2, 0x46, 0x9c, 0x2a, 0x63, 0x30, 0x7a, 0xae, 0x55, 0xd3, 0x04,
	0x4b, 0x54, 0x16, 0x57, 0xc5, 0xed, 0xf1, 0xfb, 0xc9, 0x38, 0x7e, 0x1a, 0xa6, 0xf2, 0x4e, 0x9c,
	0x1b, 0xf4, 0x64, 0x3d, 0x45, 0x9a, 0x7d, 0x53, 0xee, 0xe5, 0x5a, 0x4e, 0x77, 0xd3, 0xdb, 0xf2,
	0x41, 0x5c, 0x7a, 0xcb, 0x3f, 0x18, 0x36, 0x35, 0x41, 0xeb, 0xc1, 0xb7, 0x73, 0xb7, 0x9f, 0xdd,
	0xc5, 0x58, 0x7c, 0x0c, 0xc1, 0x3f, 0x7e, 0x14, 0x8b, 0x1d, 0x86, 0xc6, 0x7a, 0x06, 0x4e, 0x73,
	0x7d, 0x90, 0x75, 0x39, 0x26, 0x2f, 0x63, 0x31, 0xf1, 0xe7, 0xf5, 0xd7, 0x7d, 0x0b, 0xfc, 0x1d,
	0xf5, 0xca, 0x60, 0x57, 0x41, 0xd7, 0x45, 0x56, 0x1a, 0x1c, 0x70, 0x5a, 0x02, 0x56, 0x5b, 0x15,
	0x1d, 0x2f, 0x1d, 0xe8, 0xa0, 0xaa, 0xe1, 0x6c, 0x43, 0x6f, 0xf4, 0x51, 0xde, 0xd8, 0xfa, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0x8d, 0xdd, 0x4c, 0x01, 0x50, 0x01, 0x00, 0x00,
}
