// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaveTransactionsRequest struct {
	// Transactions to persist.
	TxnsToCommit []*TransactionToCommit `protobuf:"bytes,1,rep,name=txns_to_commit,json=txnsToCommit,proto3" json:"txns_to_commit,omitempty"`
	// The version of the first transaction in `txns_to_commit`.
	FirstVersion uint64 `protobuf:"varint,2,opt,name=first_version,json=firstVersion,proto3" json:"first_version,omitempty"`
	// If this is set, Storage will check its state after applying the above
	// transactions matches info in this LedgerInfo before committing otherwise
	// it denies the request.
	LedgerInfoWithSignatures *LedgerInfoWithSignatures `protobuf:"bytes,3,opt,name=ledger_info_with_signatures,json=ledgerInfoWithSignatures,proto3" json:"ledger_info_with_signatures,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *SaveTransactionsRequest) Reset()         { *m = SaveTransactionsRequest{} }
func (m *SaveTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*SaveTransactionsRequest) ProtoMessage()    {}
func (*SaveTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *SaveTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveTransactionsRequest.Unmarshal(m, b)
}
func (m *SaveTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *SaveTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveTransactionsRequest.Merge(m, src)
}
func (m *SaveTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_SaveTransactionsRequest.Size(m)
}
func (m *SaveTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveTransactionsRequest proto.InternalMessageInfo

func (m *SaveTransactionsRequest) GetTxnsToCommit() []*TransactionToCommit {
	if m != nil {
		return m.TxnsToCommit
	}
	return nil
}

func (m *SaveTransactionsRequest) GetFirstVersion() uint64 {
	if m != nil {
		return m.FirstVersion
	}
	return 0
}

func (m *SaveTransactionsRequest) GetLedgerInfoWithSignatures() *LedgerInfoWithSignatures {
	if m != nil {
		return m.LedgerInfoWithSignatures
	}
	return nil
}

type SaveTransactionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveTransactionsResponse) Reset()         { *m = SaveTransactionsResponse{} }
func (m *SaveTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*SaveTransactionsResponse) ProtoMessage()    {}
func (*SaveTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *SaveTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveTransactionsResponse.Unmarshal(m, b)
}
func (m *SaveTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *SaveTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveTransactionsResponse.Merge(m, src)
}
func (m *SaveTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_SaveTransactionsResponse.Size(m)
}
func (m *SaveTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveTransactionsResponse proto.InternalMessageInfo

type GetTransactionsRequest struct {
	// The version to start with.
	StartVersion uint64 `protobuf:"varint,1,opt,name=start_version,json=startVersion,proto3" json:"start_version,omitempty"`
	// The size of the transaction batch.
	BatchSize uint64 `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// All the proofs returned in the response should be relative to this
	// given version.
	LedgerVersion uint64 `protobuf:"varint,3,opt,name=ledger_version,json=ledgerVersion,proto3" json:"ledger_version,omitempty"`
	// Used to return the events associated with each transaction
	FetchEvents          bool     `protobuf:"varint,4,opt,name=fetch_events,json=fetchEvents,proto3" json:"fetch_events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionsRequest) Reset()         { *m = GetTransactionsRequest{} }
func (m *GetTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsRequest) ProtoMessage()    {}
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *GetTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsRequest.Unmarshal(m, b)
}
func (m *GetTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsRequest.Merge(m, src)
}
func (m *GetTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsRequest.Size(m)
}
func (m *GetTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsRequest proto.InternalMessageInfo

func (m *GetTransactionsRequest) GetStartVersion() uint64 {
	if m != nil {
		return m.StartVersion
	}
	return 0
}

func (m *GetTransactionsRequest) GetBatchSize() uint64 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *GetTransactionsRequest) GetLedgerVersion() uint64 {
	if m != nil {
		return m.LedgerVersion
	}
	return 0
}

func (m *GetTransactionsRequest) GetFetchEvents() bool {
	if m != nil {
		return m.FetchEvents
	}
	return false
}

type GetTransactionsResponse struct {
	TxnListWithProof     *TransactionListWithProof `protobuf:"bytes,1,opt,name=txn_list_with_proof,json=txnListWithProof,proto3" json:"txn_list_with_proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetTransactionsResponse) Reset()         { *m = GetTransactionsResponse{} }
func (m *GetTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsResponse) ProtoMessage()    {}
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *GetTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsResponse.Unmarshal(m, b)
}
func (m *GetTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsResponse.Merge(m, src)
}
func (m *GetTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsResponse.Size(m)
}
func (m *GetTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsResponse proto.InternalMessageInfo

func (m *GetTransactionsResponse) GetTxnListWithProof() *TransactionListWithProof {
	if m != nil {
		return m.TxnListWithProof
	}
	return nil
}

type GetAccountStateWithProofByStateRootRequest struct {
	/// The account address to query with.
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	/// The state root hash the query is based on.
	StateRootHash        []byte   `protobuf:"bytes,2,opt,name=state_root_hash,json=stateRootHash,proto3" json:"state_root_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountStateWithProofByStateRootRequest) Reset() {
	*m = GetAccountStateWithProofByStateRootRequest{}
}
func (m *GetAccountStateWithProofByStateRootRequest) String() string {
	return proto.CompactTextString(m)
}
func (*GetAccountStateWithProofByStateRootRequest) ProtoMessage() {}
func (*GetAccountStateWithProofByStateRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}

func (m *GetAccountStateWithProofByStateRootRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountStateWithProofByStateRootRequest.Unmarshal(m, b)
}
func (m *GetAccountStateWithProofByStateRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountStateWithProofByStateRootRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountStateWithProofByStateRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountStateWithProofByStateRootRequest.Merge(m, src)
}
func (m *GetAccountStateWithProofByStateRootRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountStateWithProofByStateRootRequest.Size(m)
}
func (m *GetAccountStateWithProofByStateRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountStateWithProofByStateRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountStateWithProofByStateRootRequest proto.InternalMessageInfo

func (m *GetAccountStateWithProofByStateRootRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GetAccountStateWithProofByStateRootRequest) GetStateRootHash() []byte {
	if m != nil {
		return m.StateRootHash
	}
	return nil
}

type GetAccountStateWithProofByStateRootResponse struct {
	/// The optional blob of account state blob.
	AccountStateBlob *AccountStateBlob `protobuf:"bytes,1,opt,name=account_state_blob,json=accountStateBlob,proto3" json:"account_state_blob,omitempty"`
	/// The state root hash the query is based on.
	SparseMerkleProof    *SparseMerkleProof `protobuf:"bytes,2,opt,name=sparse_merkle_proof,json=sparseMerkleProof,proto3" json:"sparse_merkle_proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetAccountStateWithProofByStateRootResponse) Reset() {
	*m = GetAccountStateWithProofByStateRootResponse{}
}
func (m *GetAccountStateWithProofByStateRootResponse) String() string {
	return proto.CompactTextString(m)
}
func (*GetAccountStateWithProofByStateRootResponse) ProtoMessage() {}
func (*GetAccountStateWithProofByStateRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5}
}

func (m *GetAccountStateWithProofByStateRootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountStateWithProofByStateRootResponse.Unmarshal(m, b)
}
func (m *GetAccountStateWithProofByStateRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountStateWithProofByStateRootResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountStateWithProofByStateRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountStateWithProofByStateRootResponse.Merge(m, src)
}
func (m *GetAccountStateWithProofByStateRootResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountStateWithProofByStateRootResponse.Size(m)
}
func (m *GetAccountStateWithProofByStateRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountStateWithProofByStateRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountStateWithProofByStateRootResponse proto.InternalMessageInfo

func (m *GetAccountStateWithProofByStateRootResponse) GetAccountStateBlob() *AccountStateBlob {
	if m != nil {
		return m.AccountStateBlob
	}
	return nil
}

func (m *GetAccountStateWithProofByStateRootResponse) GetSparseMerkleProof() *SparseMerkleProof {
	if m != nil {
		return m.SparseMerkleProof
	}
	return nil
}

type GetExecutorStartupInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExecutorStartupInfoRequest) Reset()         { *m = GetExecutorStartupInfoRequest{} }
func (m *GetExecutorStartupInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetExecutorStartupInfoRequest) ProtoMessage()    {}
func (*GetExecutorStartupInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6}
}

func (m *GetExecutorStartupInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExecutorStartupInfoRequest.Unmarshal(m, b)
}
func (m *GetExecutorStartupInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExecutorStartupInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetExecutorStartupInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExecutorStartupInfoRequest.Merge(m, src)
}
func (m *GetExecutorStartupInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetExecutorStartupInfoRequest.Size(m)
}
func (m *GetExecutorStartupInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExecutorStartupInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetExecutorStartupInfoRequest proto.InternalMessageInfo

type GetExecutorStartupInfoResponse struct {
	// When this is empty, Storage needs to be bootstrapped via the bootstrap API
	Info                 *ExecutorStartupInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetExecutorStartupInfoResponse) Reset()         { *m = GetExecutorStartupInfoResponse{} }
func (m *GetExecutorStartupInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetExecutorStartupInfoResponse) ProtoMessage()    {}
func (*GetExecutorStartupInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{7}
}

func (m *GetExecutorStartupInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExecutorStartupInfoResponse.Unmarshal(m, b)
}
func (m *GetExecutorStartupInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExecutorStartupInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetExecutorStartupInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExecutorStartupInfoResponse.Merge(m, src)
}
func (m *GetExecutorStartupInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetExecutorStartupInfoResponse.Size(m)
}
func (m *GetExecutorStartupInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExecutorStartupInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetExecutorStartupInfoResponse proto.InternalMessageInfo

func (m *GetExecutorStartupInfoResponse) GetInfo() *ExecutorStartupInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ExecutorStartupInfo struct {
	// The latest LedgerInfo. Note that at start up storage can have more
	// transactions than the latest LedgerInfo indicates due to an incomplete
	// start up sync.
	LedgerInfo *LedgerInfo `protobuf:"bytes,1,opt,name=ledger_info,json=ledgerInfo,proto3" json:"ledger_info,omitempty"`
	// The latest version. All fields below are based on this version.
	LatestVersion uint64 `protobuf:"varint,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	// The latest account state root hash.
	AccountStateRootHash []byte `protobuf:"bytes,3,opt,name=account_state_root_hash,json=accountStateRootHash,proto3" json:"account_state_root_hash,omitempty"`
	// From left to right, root hashes of all frozen subtrees.
	LedgerFrozenSubtreeHashes [][]byte `protobuf:"bytes,4,rep,name=ledger_frozen_subtree_hashes,json=ledgerFrozenSubtreeHashes,proto3" json:"ledger_frozen_subtree_hashes,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *ExecutorStartupInfo) Reset()         { *m = ExecutorStartupInfo{} }
func (m *ExecutorStartupInfo) String() string { return proto.CompactTextString(m) }
func (*ExecutorStartupInfo) ProtoMessage()    {}
func (*ExecutorStartupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{8}
}

func (m *ExecutorStartupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutorStartupInfo.Unmarshal(m, b)
}
func (m *ExecutorStartupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutorStartupInfo.Marshal(b, m, deterministic)
}
func (m *ExecutorStartupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutorStartupInfo.Merge(m, src)
}
func (m *ExecutorStartupInfo) XXX_Size() int {
	return xxx_messageInfo_ExecutorStartupInfo.Size(m)
}
func (m *ExecutorStartupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutorStartupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutorStartupInfo proto.InternalMessageInfo

func (m *ExecutorStartupInfo) GetLedgerInfo() *LedgerInfo {
	if m != nil {
		return m.LedgerInfo
	}
	return nil
}

func (m *ExecutorStartupInfo) GetLatestVersion() uint64 {
	if m != nil {
		return m.LatestVersion
	}
	return 0
}

func (m *ExecutorStartupInfo) GetAccountStateRootHash() []byte {
	if m != nil {
		return m.AccountStateRootHash
	}
	return nil
}

func (m *ExecutorStartupInfo) GetLedgerFrozenSubtreeHashes() [][]byte {
	if m != nil {
		return m.LedgerFrozenSubtreeHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*SaveTransactionsRequest)(nil), "storage.SaveTransactionsRequest")
	proto.RegisterType((*SaveTransactionsResponse)(nil), "storage.SaveTransactionsResponse")
	proto.RegisterType((*GetTransactionsRequest)(nil), "storage.GetTransactionsRequest")
	proto.RegisterType((*GetTransactionsResponse)(nil), "storage.GetTransactionsResponse")
	proto.RegisterType((*GetAccountStateWithProofByStateRootRequest)(nil), "storage.GetAccountStateWithProofByStateRootRequest")
	proto.RegisterType((*GetAccountStateWithProofByStateRootResponse)(nil), "storage.GetAccountStateWithProofByStateRootResponse")
	proto.RegisterType((*GetExecutorStartupInfoRequest)(nil), "storage.GetExecutorStartupInfoRequest")
	proto.RegisterType((*GetExecutorStartupInfoResponse)(nil), "storage.GetExecutorStartupInfoResponse")
	proto.RegisterType((*ExecutorStartupInfo)(nil), "storage.ExecutorStartupInfo")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xd3, 0x48,
	0x14, 0x96, 0x9b, 0x68, 0xbb, 0x7b, 0x92, 0xf4, 0x67, 0x5a, 0x6d, 0xbc, 0xde, 0x76, 0x9b, 0x3a,
	0xda, 0x12, 0x81, 0x14, 0xa1, 0x14, 0xae, 0x81, 0xa2, 0xd2, 0x22, 0x15, 0x84, 0xec, 0x40, 0xef,
	0xb0, 0x26, 0xc9, 0x49, 0x62, 0x91, 0x7a, 0xc2, 0xcc, 0x49, 0x49, 0xfb, 0x14, 0xdc, 0xf1, 0x06,
	0x3c, 0x06, 0xcf, 0xc2, 0x25, 0x8f, 0x81, 0x3c, 0x1e, 0x27, 0x6e, 0x7e, 0x4a, 0xb9, 0xf4, 0x37,
	0xdf, 0x7c, 0x73, 0xbe, 0x6f, 0xce, 0x19, 0x43, 0x49, 0x91, 0x90, 0xbc, 0x87, 0xf5, 0xa1, 0x14,
	0x24, 0xd8, 0xaa, 0xf9, 0x74, 0xb6, 0x7b, 0x48, 0xc1, 0xa7, 0x90, 0xfa, 0xc1, 0x50, 0x0a, 0xd1,
	0x4d, 0x96, 0x9d, 0xcd, 0x01, 0x76, 0x7a, 0x28, 0x83, 0x30, 0xea, 0x8a, 0x14, 0x22, 0xc9, 0x23,
	0xc5, 0xdb, 0x14, 0x8a, 0xc8, 0x40, 0x36, 0x6f, 0xb7, 0xc5, 0x28, 0xa2, 0x40, 0x11, 0x27, 0x0c,
	0x5a, 0x03, 0xd1, 0x32, 0x2b, 0x85, 0x8c, 0x98, 0xfb, 0xdd, 0x82, 0xb2, 0xcf, 0x2f, 0xb1, 0x39,
	0x15, 0x50, 0x1e, 0x7e, 0x1c, 0xa1, 0x22, 0xf6, 0x14, 0xd6, 0x68, 0x1c, 0xa9, 0x80, 0x44, 0xd0,
	0x16, 0x17, 0x17, 0x21, 0xd9, 0x56, 0x25, 0x57, 0x2b, 0x34, 0x9c, 0x3a, 0x5d, 0x0d, 0x51, 0xd5,
	0x33, 0x7b, 0x9a, 0xe2, 0xb9, 0x66, 0x78, 0xc5, 0x78, 0x47, 0xfa, 0xc5, 0xaa, 0x50, 0xea, 0x86,
	0x52, 0x51, 0x70, 0x89, 0x52, 0x85, 0x22, 0xb2, 0x57, 0x2a, 0x56, 0x2d, 0xef, 0x15, 0x35, 0xf8,
	0x2e, 0xc1, 0xd8, 0x7b, 0xf8, 0x37, 0xe3, 0x28, 0xf1, 0xab, 0xc2, 0x5e, 0xc4, 0x69, 0x24, 0x51,
	0xd9, 0xb9, 0x8a, 0x55, 0x2b, 0x34, 0xf6, 0xcc, 0x99, 0x67, 0x9a, 0xf9, 0x32, 0xea, 0x8a, 0xf3,
	0x90, 0xfa, 0xfe, 0x84, 0xe6, 0xd9, 0x83, 0x25, 0x2b, 0xae, 0x03, 0xf6, 0xbc, 0x43, 0x35, 0x14,
	0x91, 0x42, 0xf7, 0xab, 0x05, 0x7f, 0x9f, 0x20, 0x2d, 0x72, 0x5f, 0x8d, 0xaf, 0x85, 0xcb, 0x69,
	0xed, 0x56, 0x52, 0xbb, 0x06, 0xd3, 0xda, 0x77, 0x01, 0x5a, 0x9c, 0xda, 0x71, 0xc1, 0xd7, 0x68,
	0xdc, 0xfd, 0xa5, 0x11, 0x3f, 0xbc, 0x46, 0xf6, 0x3f, 0xac, 0x19, 0x6b, 0xa9, 0x48, 0x4e, 0x53,
	0x4a, 0x09, 0x9a, 0xaa, 0xec, 0x43, 0xb1, 0x8b, 0xb1, 0x0a, 0x5e, 0x62, 0x44, 0xca, 0xce, 0x57,
	0xac, 0xda, 0x9f, 0x5e, 0x41, 0x63, 0xc7, 0x1a, 0x72, 0x43, 0x28, 0xcf, 0xd5, 0x99, 0x78, 0x60,
	0xaf, 0x61, 0x8b, 0xc6, 0x51, 0x30, 0x08, 0x55, 0xb6, 0x59, 0x74, 0xb9, 0xd3, 0xdc, 0x32, 0x3b,
	0xcf, 0x42, 0x45, 0x71, 0x44, 0x6f, 0x62, 0x9a, 0xb7, 0x41, 0xe3, 0x9b, 0x88, 0x1b, 0xc1, 0xfd,
	0x13, 0xa4, 0x67, 0x49, 0xfb, 0xf8, 0x71, 0xf7, 0x4c, 0xd6, 0x8e, 0xae, 0xf4, 0xb7, 0x27, 0x04,
	0xa5, 0x31, 0xd9, 0xb0, 0xca, 0x3b, 0x1d, 0x89, 0x4a, 0xe9, 0x13, 0x8b, 0x5e, 0xfa, 0xc9, 0x0e,
	0x60, 0x3d, 0xe9, 0x3d, 0x29, 0x04, 0x05, 0x7d, 0xae, 0xfa, 0x3a, 0xa0, 0xa2, 0x57, 0x52, 0xa9,
	0xc8, 0x29, 0x57, 0x7d, 0xf7, 0x9b, 0x05, 0x0f, 0xee, 0x74, 0xa0, 0xf1, 0x7b, 0x0c, 0x6c, 0xbe,
	0xb7, 0x8d, 0xdd, 0xb2, 0xb1, 0x9b, 0x15, 0x3b, 0x1a, 0x88, 0x96, 0xb7, 0xc1, 0x67, 0x10, 0x76,
	0x0a, 0x5b, 0x6a, 0xc8, 0xa5, 0xc2, 0xe0, 0x02, 0xe5, 0x87, 0x01, 0x9a, 0xd8, 0x56, 0xb4, 0x8e,
	0x6d, 0x74, 0x7c, 0xcd, 0x78, 0xa5, 0x09, 0x49, 0x5e, 0x9b, 0x6a, 0x16, 0x72, 0xf7, 0x60, 0xf7,
	0x04, 0xe9, 0x78, 0x8c, 0xed, 0x11, 0x09, 0xe9, 0xc7, 0xfd, 0x31, 0x1a, 0xc6, 0x8d, 0x68, 0x32,
	0x72, 0x3d, 0xf8, 0x6f, 0x19, 0xc1, 0x78, 0x7a, 0x08, 0xf9, 0xb8, 0xf9, 0x8d, 0x8b, 0x9d, 0x7a,
	0xfa, 0x20, 0x2c, 0xda, 0xa3, 0x99, 0xee, 0x0f, 0x0b, 0xb6, 0x16, 0xac, 0xb2, 0x06, 0x14, 0x32,
	0xd3, 0x64, 0x04, 0x37, 0xe7, 0xa6, 0xc7, 0x83, 0xe9, 0xbc, 0xe8, 0x36, 0xe5, 0x84, 0x73, 0x73,
	0x5a, 0x4a, 0xd0, 0xb4, 0x4d, 0x1f, 0x43, 0xf9, 0x66, 0xf0, 0xd3, 0x8b, 0xcd, 0xe9, 0x8b, 0xdd,
	0xce, 0x86, 0x9c, 0xde, 0x2f, 0x7b, 0x02, 0x3b, 0xa6, 0xa2, 0xae, 0x14, 0xd7, 0x18, 0x05, 0x6a,
	0xd4, 0x22, 0x89, 0xa8, 0x77, 0x62, 0xdc, 0xed, 0xb9, 0x5a, 0xd1, 0xfb, 0x27, 0xe1, 0xbc, 0xd0,
	0x14, 0x3f, 0x61, 0x9c, 0x6a, 0x42, 0xe3, 0x4b, 0x1e, 0x56, 0xfd, 0x24, 0x10, 0x76, 0x0e, 0x1b,
	0xb3, 0xc3, 0xcc, 0x2a, 0x93, 0xb8, 0x96, 0xbc, 0x64, 0xce, 0xfe, 0x2d, 0x0c, 0x73, 0x03, 0x01,
	0x6c, 0xbf, 0x1d, 0x76, 0x38, 0x61, 0x53, 0x9c, 0x69, 0xd7, 0x49, 0x56, 0xcc, 0x35, 0xd1, 0x2d,
	0x5a, 0x4c, 0xe5, 0xab, 0xb7, 0x72, 0xcc, 0x01, 0x4d, 0x58, 0x9f, 0x99, 0x60, 0xb6, 0x37, 0x29,
	0x6b, 0xf1, 0x1b, 0xe4, 0x54, 0x96, 0x13, 0x8c, 0xea, 0x67, 0x0b, 0xaa, 0x77, 0x18, 0x1e, 0x76,
	0x98, 0x55, 0xba, 0xe3, 0x6c, 0x3b, 0x8f, 0x7e, 0x6f, 0x93, 0x29, 0x29, 0xd4, 0x4f, 0xea, 0xa2,
	0xde, 0x3c, 0xc8, 0xea, 0x2d, 0x9f, 0x17, 0xe7, 0xde, 0x2f, 0x79, 0xc9, 0x51, 0xad, 0x3f, 0xf4,
	0x4f, 0xec, 0xf0, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0x47, 0x12, 0x48, 0x41, 0x07, 0x00,
	0x00,
}
